### ISSUE TITLE
Incorrect syntax for plotting series

### ISSUE THREAD

**Issue by jasperino64** [learn-co-curriculum/dsc-pandas-series-and-dataframes-lab#4]
## Link to Canvas

https://flatiron.illumidesk.com/user/jasperschen/notebooks/dsc-pandas-series-and-dataframes-lab/index.ipynb#

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

`wkend[['entries', 'exits']].plot(kind='barh')
# does not work
#should be:
wkend.plot(kind='barh')
```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ x] IllumiDesk

**Comment by jessepisel** [comment]
Thanks for opening this issue @Jasperino64 :wave:. I am not able to replicate this locally or on Saturn Cloud. You should double check your code with the `solution` branch here on GitHub to make sure you are reshaping your data correctly. 

I am closing this issue at this time.
